access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: create
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/edubin
    username: postgres
    password: admin